"""
Read-only API service for ROY dashboard consumption.

Serves latest and historical prediction artifacts generated by train_model.py.
"""
from pathlib import Path
import json
from typing import Optional

import pandas as pd
import numpy as np
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse

ROOT = Path(__file__).resolve().parents[1]
PRED_DIR = ROOT / "predictions"
OUT_DIR = ROOT / "outputs"
HISTORY_DIR = PRED_DIR / "history"
RACE_ODDS_TOLERANCE = 1e-3

app = FastAPI(title="ROY Dashboard API", version="1.0.0")


def _error(code: str, message: str, details=None):
    return {"error": {"code": code, "message": message, "details": details}}


def _load_json(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(str(path))
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(str(path))
    return pd.read_csv(path)


def _snake_columns(df: pd.DataFrame) -> pd.DataFrame:
    rename_map = {
        "PLAYER_ID": "player_id",
        "PLAYER_NAME": "player_name",
        "SEASON": "season",
        "TEAM": "team",
        "TEAM_ID": "team_id",
        "POSITION": "position",
        "race_odds": "race_odds",
        "prob_roy_raw": "prob_roy_raw",
        "run_id": "run_id",
        "run_timestamp_utc": "run_timestamp_utc",
        "git_commit": "git_commit",
        "rank": "rank",
        "PTS_per_game": "pts_per_game",
        "REB_per_game": "reb_per_game",
        "AST_per_game": "ast_per_game",
        "MIN_per_game": "min_per_game",
        "TS": "ts",
        "USG_RATE": "usg_rate",
        "TEAM_WIN_PCT": "team_win_pct",
        "POINTS_SHARE": "points_share",
        "MINUTES_SHARE": "minutes_share",
        "DRAFT_PICK_LOG": "draft_pick_log",
    }
    out = df.copy()
    out = out.rename(columns=rename_map)
    out.columns = [c.lower() for c in out.columns]
    return out


def _required_cols(df: pd.DataFrame, cols: list[str]):
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def _latest_run_info() -> dict:
    return _load_json(OUT_DIR / "run_info.json")


def _latest_predictions() -> pd.DataFrame:
    df = _snake_columns(_load_csv(PRED_DIR / "predictions.csv"))
    _required_cols(df, ["player_id", "player_name", "season", "race_odds"])
    return df


def _all_predictions() -> pd.DataFrame:
    df = _snake_columns(_load_csv(PRED_DIR / "roy_predictions_all_seasons.csv"))
    _required_cols(df, ["player_id", "player_name", "season", "race_odds"])
    return df


def _history_run_ids() -> list[str]:
    if not HISTORY_DIR.exists():
        return []
    runs = [p.name for p in HISTORY_DIR.iterdir() if p.is_dir()]
    return sorted(runs)


def _history_predictions(run_id: str) -> pd.DataFrame:
    run_path = HISTORY_DIR / run_id / "predictions.csv"
    df = _snake_columns(_load_csv(run_path))
    _required_cols(df, ["player_id", "season", "race_odds"])
    return df


def _season_or_default(df: pd.DataFrame, season: Optional[str], default_season: Optional[str]) -> str:
    if season:
        return season
    if default_season:
        return default_season
    seasons = sorted(df["season"].dropna().astype(str).unique().tolist())
    if not seasons:
        raise ValueError("No season values available.")
    return seasons[-1]


def _coerce_numeric(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


def _draft_tier_from_log(value):
    if pd.isna(value):
        return None
    pick = float(np.expm1(value))
    if pick <= 3:
        return "Top 3"
    if pick <= 14:
        return "Lottery"
    if pick <= 20:
        return "Mid First"
    if pick <= 30:
        return "Late First"
    if pick <= 60:
        return "Second Round"
    return "Undrafted"


def _apply_trend(df: pd.DataFrame, season: str) -> pd.DataFrame:
    out = df.copy()
    out["trend_delta"] = 0.0
    out["trend_direction"] = "flat"
    run_ids = _history_run_ids()
    if len(run_ids) < 2:
        out["trend_direction"] = "new"
        return out

    latest_run = run_ids[-1]
    prev_run = run_ids[-2]
    try:
        prev_df = _history_predictions(prev_run)
    except Exception:
        out["trend_direction"] = "new"
        return out

    prev_df = _coerce_numeric(prev_df, ["race_odds"])
    prev_df = prev_df[prev_df["season"].astype(str) == str(season)][["player_id", "race_odds"]].copy()
    prev_df = prev_df.rename(columns={"race_odds": "prev_race_odds"})
    out = out.merge(prev_df, on="player_id", how="left")
    out["prev_race_odds"] = pd.to_numeric(out["prev_race_odds"], errors="coerce")
    out["race_odds"] = pd.to_numeric(out["race_odds"], errors="coerce")
    out["trend_delta"] = (out["race_odds"] - out["prev_race_odds"]).fillna(0.0)
    out["trend_direction"] = out["trend_delta"].apply(lambda x: "up" if x > 0 else ("down" if x < 0 else "flat"))
    out.loc[out["prev_race_odds"].isna(), "trend_direction"] = "new"
    out = out.drop(columns=["prev_race_odds"])
    return out


@app.exception_handler(FileNotFoundError)
async def file_not_found_handler(_, exc: FileNotFoundError):
    return JSONResponse(status_code=404, content=_error("NOT_FOUND", "Required artifact file not found.", str(exc)))


@app.exception_handler(HTTPException)
async def http_exception_handler(_, exc: HTTPException):
    if isinstance(exc.detail, dict) and "error" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return JSONResponse(
        status_code=exc.status_code,
        content=_error("HTTP_ERROR", str(exc.detail), None),
    )


@app.exception_handler(ValueError)
async def value_error_handler(_, exc: ValueError):
    return JSONResponse(status_code=422, content=_error("VALIDATION_ERROR", str(exc), None))


@app.get("/health/live")
def health_live():
    return {"status": "ok"}


@app.get("/health/ready")
def health_ready():
    run_info = _latest_run_info()
    latest = _latest_predictions()
    season = str(run_info.get("current_season", ""))
    season_df = latest[latest["season"].astype(str) == season].copy()
    odds_sum = float(pd.to_numeric(season_df.get("race_odds", 0), errors="coerce").fillna(0).sum()) if not season_df.empty else 0.0
    passed = bool(abs(odds_sum - 1.0) <= RACE_ODDS_TOLERANCE) if not season_df.empty else False
    return {
        "status": "ready" if passed else "degraded",
        "run_id": run_info.get("run_id"),
        "season": season,
        "odds_sum_current_season": odds_sum,
        "odds_sum_check_passed": passed,
    }


@app.get("/api/v1/runs/latest")
def get_runs_latest():
    run_info = _latest_run_info()
    latest_df = _latest_predictions()
    season = str(run_info.get("current_season", ""))
    season_df = latest_df[latest_df["season"].astype(str) == season].copy()
    odds_sum = float(pd.to_numeric(season_df.get("race_odds", 0), errors="coerce").fillna(0).sum()) if not season_df.empty else 0.0
    passed = bool(abs(odds_sum - 1.0) <= RACE_ODDS_TOLERANCE) if not season_df.empty else False

    return {
        "run_id": run_info.get("run_id"),
        "run_timestamp_utc": run_info.get("run_timestamp_utc"),
        "season": season,
        "model_name": run_info.get("selected_model"),
        "probability_presentation": run_info.get("probability_presentation"),
        "record_count": int(len(season_df)),
        "odds_sum_current_season": odds_sum,
        "odds_sum_check_passed": passed,
        "source_files": {
            "predictions": str(PRED_DIR / "predictions.csv"),
            "run_info": str(OUT_DIR / "run_info.json"),
        },
    }


@app.get("/api/v1/leaderboard")
def get_leaderboard(
    season: Optional[str] = None,
    top_n: int = Query(default=10, ge=1, le=50),
    team: Optional[str] = None,
    position: Optional[str] = None,
    draft_tier: Optional[str] = None,
):
    run_info = _latest_run_info()
    df = _latest_predictions()
    season_value = _season_or_default(df, season, run_info.get("current_season"))
    df = df[df["season"].astype(str) == str(season_value)].copy()
    if df.empty:
        raise HTTPException(status_code=404, detail=_error("NOT_FOUND", f"No predictions found for season {season_value}.", None))

    numeric_cols = [
        "race_odds", "prob_roy_raw", "pts_per_game", "reb_per_game", "ast_per_game",
        "ts", "usg_rate", "min_per_game", "team_win_pct", "points_share", "minutes_share",
        "draft_pick_log", "rank",
    ]
    df = _coerce_numeric(df, numeric_cols)

    if "draft_pick_log" in df.columns:
        df["draft_tier_display"] = df["draft_pick_log"].apply(_draft_tier_from_log)
    else:
        df["draft_tier_display"] = None

    if team and "team" in df.columns:
        df = df[df["team"].astype(str).str.upper() == team.upper()]
    if position and "position" in df.columns:
        df = df[df["position"].astype(str).str.upper() == position.upper()]
    if draft_tier:
        df = df[df["draft_tier_display"] == draft_tier]

    if df.empty:
        return {
            "run_id": run_info.get("run_id"),
            "run_timestamp_utc": run_info.get("run_timestamp_utc"),
            "season": season_value,
            "top_n": top_n,
            "odds_sum_current_season": 0.0,
            "rows": [],
        }

    if "rank" not in df.columns or df["rank"].isna().all():
        df["rank"] = df["race_odds"].rank(method="min", ascending=False).astype(int)
    df = _apply_trend(df, str(season_value))
    df = df.sort_values(["race_odds", "player_name"], ascending=[False, True]).head(top_n)
    odds_sum = float(df["race_odds"].fillna(0).sum())

    fields = [
        "rank", "player_id", "player_name", "team", "position", "race_odds", "prob_roy_raw",
        "trend_direction", "trend_delta", "pts_per_game", "reb_per_game", "ast_per_game",
        "ts", "usg_rate", "min_per_game", "team_win_pct", "points_share", "minutes_share",
        "draft_pick_log", "draft_tier_display",
    ]
    for c in fields:
        if c not in df.columns:
            df[c] = None

    rows = df[fields].to_dict(orient="records")
    return {
        "run_id": run_info.get("run_id"),
        "run_timestamp_utc": run_info.get("run_timestamp_utc"),
        "season": season_value,
        "top_n": top_n,
        "odds_sum_current_season": odds_sum,
        "rows": rows,
    }


@app.get("/api/v1/player/{player_id}")
def get_player(player_id: int, season: Optional[str] = None):
    run_info = _latest_run_info()
    df = _latest_predictions()
    season_value = _season_or_default(df, season, run_info.get("current_season"))
    season_df = df[df["season"].astype(str) == str(season_value)].copy()
    if season_df.empty:
        raise HTTPException(status_code=404, detail=_error("NOT_FOUND", f"No predictions found for season {season_value}.", None))

    numeric_cols = ["race_odds", "prob_roy_raw", "pts_per_game", "reb_per_game", "ast_per_game", "min_per_game", "ts", "usg_rate", "team_win_pct"]
    season_df = _coerce_numeric(season_df, numeric_cols)
    season_df["rank"] = season_df["race_odds"].rank(method="min", ascending=False).astype(int)

    row = season_df[season_df["player_id"] == player_id].copy()
    if row.empty:
        raise HTTPException(status_code=404, detail=_error("NOT_FOUND", f"Player {player_id} not found for season {season_value}.", None))
    r = row.iloc[0].to_dict()

    rank_fields = {}
    rank_map = {
        "pts_per_game": "pts_per_game_rank",
        "min_per_game": "min_per_game_rank",
        "ts": "ts_rank",
        "usg_rate": "usg_rate_rank",
        "team_win_pct": "team_win_pct_rank",
    }
    for src, dst in rank_map.items():
        if src in season_df.columns:
            season_df[f"__{dst}"] = season_df[src].rank(method="min", ascending=False)
            val = season_df.loc[season_df["player_id"] == player_id, f"__{dst}"]
            rank_fields[dst] = int(val.iloc[0]) if not val.empty and pd.notna(val.iloc[0]) else None
        else:
            rank_fields[dst] = None

    return {
        "run_id": run_info.get("run_id"),
        "run_timestamp_utc": run_info.get("run_timestamp_utc"),
        "season": season_value,
        "player": {
            "player_id": int(r.get("player_id")),
            "player_name": r.get("player_name"),
            "team": r.get("team"),
            "position": r.get("position"),
            "rank": int(r.get("rank")) if pd.notna(r.get("rank")) else None,
            "race_odds": float(r.get("race_odds")) if pd.notna(r.get("race_odds")) else None,
            "prob_roy_raw": float(r.get("prob_roy_raw")) if pd.notna(r.get("prob_roy_raw")) else None,
            "stats": {
                "pts_per_game": r.get("pts_per_game"),
                "reb_per_game": r.get("reb_per_game"),
                "ast_per_game": r.get("ast_per_game"),
                "min_per_game": r.get("min_per_game"),
                "ts": r.get("ts"),
                "usg_rate": r.get("usg_rate"),
                "team_win_pct": r.get("team_win_pct"),
                "points_share": r.get("points_share"),
                "minutes_share": r.get("minutes_share"),
            },
        },
        "rookie_comparison": {"field_ranks": rank_fields},
        "feature_contributions": None,
    }


@app.get("/api/v1/trends")
def get_trends(season: str, player_id: int):
    run_ids = _history_run_ids()
    if not run_ids:
        raise HTTPException(status_code=404, detail=_error("NOT_FOUND", "No history snapshots found.", None))

    series = []
    for run_id in run_ids:
        try:
            df = _history_predictions(run_id)
        except Exception:
            continue
        df = _coerce_numeric(df, ["race_odds", "rank", "player_id"])
        row = df[(df["season"].astype(str) == str(season)) & (df["player_id"] == player_id)]
        if row.empty:
            continue
        record = row.iloc[0]
        series.append(
            {
                "run_id": run_id,
                "run_timestamp_utc": record.get("run_timestamp_utc"),
                "race_odds": float(record.get("race_odds")) if pd.notna(record.get("race_odds")) else None,
                "rank": int(record.get("rank")) if pd.notna(record.get("rank")) else None,
            }
        )

    if not series:
        raise HTTPException(
            status_code=404,
            detail=_error("NOT_FOUND", f"No trend data for player {player_id} in season {season}.", None),
        )

    latest_df = _latest_predictions()
    player_name = latest_df.loc[latest_df["player_id"] == player_id, "player_name"]
    return {
        "season": season,
        "player_id": player_id,
        "player_name": player_name.iloc[0] if not player_name.empty else None,
        "series": series,
    }


@app.get("/api/v1/filters")
def get_filters(season: Optional[str] = None):
    run_info = _latest_run_info()
    df = _latest_predictions()
    season_value = _season_or_default(df, season, run_info.get("current_season"))
    df = df[df["season"].astype(str) == str(season_value)].copy()

    teams = sorted(df["team"].dropna().astype(str).unique().tolist()) if "team" in df.columns else []
    positions = sorted(df["position"].dropna().astype(str).unique().tolist()) if "position" in df.columns else []
    draft_tiers = []
    if "draft_pick_log" in df.columns:
        draft_tiers = sorted(
            [v for v in set(df["draft_pick_log"].apply(_draft_tier_from_log).dropna().tolist()) if v]
        )

    return {"season": season_value, "teams": teams, "positions": positions, "draft_tiers": draft_tiers}
